// AUTO-GENERATED by scripts/fetch_images.py — do not edit by hand.
export const IMAGES = {
  "kinkakuji": "kinkakuji.webp",
  "ginkakuji": "ginkakuji.webp",
  "kiyomizu": "kiyomizu.webp",
  "nonomiya": "nonomiya.webp",
  "bamboo": "bamboo.webp",
  "togetsukyo": "togetsukyo.webp",
  "himeji": "himeji.webp",
  "kix": "kix.webp"
};
export const CREDITS = [
  {
    "key": "kinkakuji",
    "title": "Kinkaku-ji golden pavilion",
    "author": "Martin Falbisoner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kinkaku-ji_in_November_2016_-02.jpg"
  },
  {
    "key": "ginkakuji",
    "title": "Ginkaku-ji",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sunlight_through_clouds_and_view_of_Ginkaku-ji_Temple_from_above,_Kyoto,_Japan.jpg"
  },
  {
    "key": "kiyomizu",
    "title": "Kiyomizu-dera main hall",
    "author": "Martin Falbisoner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kiyomizu-dera,_Kyoto,_November_2016_-01.jpg"
  },
  {
    "key": "nonomiya",
    "title": "Nonomiya Shrine Arashiyama",
    "author": "KimonBerlin",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nonomiya_shrine%3F_(11096390226).jpg"
  },
  {
    "key": "bamboo",
    "title": "Arashiyama bamboo grove",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bamboo_Forest,_Arashiyama,_Kyoto,_Japan.jpg"
  },
  {
    "key": "togetsukyo",
    "title": "Togetsukyo Bridge Arashiyama",
    "author": "DimiTalen",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_the_Katsura_River_and_the_Arashiyama_mountains_from_Togetsukyo_Bridge,_Kyoto,_2016.jpg"
  },
  {
    "key": "himeji",
    "title": "Himeji Castle",
    "author": "Bernard Gagnon",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_de_Himeji02.jpg"
  },
  {
    "key": "kix",
    "title": "Kansai International Airport",
    "author": "Carpkazu (Japanese)",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Finnair_MD-11_(OH-LGF)_taxiing_at_Kansai_International_Airport.jpg"
  }
];
