#!/usr/bin/env python3
"""Self-host Gowun Batang + Gothic A1 (woff2) from Google Fonts. FR-8, NFR-1.
Downloads every referenced woff2 subset and rewrites @font-face to local paths.
"""
import re, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "fonts"
FONT_DIR.mkdir(exist_ok=True)

# Chrome UA -> Google returns woff2 (smallest/modern)
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

FAMILIES = [
    ("Gowun Batang", "gowun-batang", "family=Gowun+Batang:wght@400;700"),
    ("Gothic A1", "gothic-a1", "family=Gothic+A1:wght@400;500;700"),
]

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=40) as r:
        return r.read()

def main():
    css_out = ["/* self-hosted fonts (offline). Generated by scripts/fetch_fonts.py */\n"]
    total = 0
    for label, slug, q in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?{q}&display=swap"
        css = fetch(url).decode("utf-8")
        # download each woff2, rewrite to local
        def repl(m, _c=[0]):
            nonlocal total
            src = m.group(1)
            _c[0] += 1
            name = f"{slug}-{_c[0]:03d}.woff2"
            try:
                data = fetch(src)
                (FONT_DIR / name).write_bytes(data)
                total += len(data)
            except Exception as e:
                print(f"  ! {name} failed: {e}")
                return m.group(0)
            return f"url('./{name}')"
        css = re.sub(r"url\((https://[^)]+\.woff2)\)", repl, css)
        css_out.append(f"/* {label} */\n{css}\n")
        print(f"[{label}] done")
    (FONT_DIR / "fonts.css").write_text("\n".join(css_out), encoding="utf-8")
    n = len(list(FONT_DIR.glob('*.woff2')))
    print(f"Wrote fonts/fonts.css + {n} woff2 ({total//1024} KB)")

if __name__ == "__main__":
    main()
